2024-09-04 16:38:21,853 [maverick_code] INFO: Lade Model 'final_parameters'.
2024-09-04 16:38:22,736 [maverick_wrapper] ERROR: index 9 is out of bounds for axis 0 with size 9
Traceback (most recent call last):
  File "/Users/nathanaelediger/Desktop/ML_ESS/Machine_learning_Ess/Bomberman/bomberman_rl/agents.py", line 248, in process_event
    event_result = getattr(module, event_name)(self.fake_self, *event_args)
  File "/Users/nathanaelediger/Desktop/ML_ESS/Machine_learning_Ess/Bomberman/bomberman_rl/agent_code/maverick/callbacks.py", line 63, in act
    features = state_to_features(self, game_state)
  File "/Users/nathanaelediger/Desktop/ML_ESS/Machine_learning_Ess/Bomberman/bomberman_rl/agent_code/maverick/ManagerFeatures.py", line 314, in state_to_features
    coin_distances_after_step[direction][int(number_of_found_coins[direction])] = distance
IndexError: index 9 is out of bounds for axis 0 with size 9
